# Generated by Django 2.2 on 2019-04-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='avatar',
            field=models.ImageField(upload_to='uploads/profile'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='cv',
            field=models.FileField(upload_to='uploads/profile'),
        ),
    ]
