# Generated by Django 2.2 on 2019-04-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0002_auto_20190416_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='avatar',
            field=models.ImageField(upload_to='uploads/profile'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='cv',
            field=models.FileField(upload_to='uploads/profile'),
        ),
    ]
