# Generated by Django 2.2 on 2019-04-16 07:02

import django.contrib.sites.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myprofile', '0002_auto_20190416_0656'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('site_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sites.Site')),
                ('site', models.CharField(blank=True, max_length=255, null=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('google_maps', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='uploads/config')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='uploads/config')),
                ('about', models.TextField(blank=True, null=True)),
                ('metatext', models.TextField(blank=True, null=True)),
                ('myprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myprofile.Myprofile')),
            ],
            bases=('sites.site',),
            managers=[
                ('objects', django.contrib.sites.models.SiteManager()),
            ],
        ),
    ]
