# Generated by Django 2.2 on 2019-04-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/config'),
        ),
        migrations.AlterField(
            model_name='config',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/config'),
        ),
    ]
